## Q2: Edges

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [4]:
import numpy as np

n=6  #number of rows
m=10 #number of columns
arr=np.zeros((n,m))

arr[0,:]=arr[:,0]=arr[n-1,:]=arr[:,m-1]=1
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Q3: Histrograms

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [16]:
import numpy as np
import matplotlib.pyplot as plt

n=10 #number of bins
data= np.loadtxt('sample.txt')
hist,edge=np.histogram(data[:,1],n)
#print(edge.shape)
for i in range (0,n):
    cent = (edge[i]+edge[i+1])/2
    print('bin ', (i+1), ' centered on ', round(cent,3), ' has counts ',hist[i])

bin  1  centered on  -27.129  has counts  3
bin  2  centered on  -20.211  has counts  4
bin  3  centered on  -13.293  has counts  9
bin  4  centered on  -6.374  has counts  22
bin  5  centered on  0.544  has counts  22
bin  6  centered on  7.462  has counts  22
bin  7  centered on  14.381  has counts  9
bin  8  centered on  21.299  has counts  7
bin  9  centered on  28.217  has counts  1
bin  10  centered on  35.136  has counts  1
